//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icasie.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conference
    {
        public Conference()
        {
            this.Participants = new HashSet<Participant>();
            this.Submissions = new HashSet<Submission>();
        }
    
        public int ConferenceId { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime PaperSubStartDate { get; set; }
        public System.DateTime PaperSubEndDate { get; set; }
        public string LastSequenceNumber { get; set; }
        public string LastParticipantNumber { get; set; }
    
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
