//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icasie.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submission
    {
        public int SubmissionId { get; set; }
        public int UserId { get; set; }
        public int ConferenceId { get; set; }
        public string Title { get; set; }
        public string FullPaperStatus { get; set; }
        public byte[] FullPaper { get; set; }
        public string FullPaperFileName { get; set; }
        public Nullable<System.DateTime> FullPaperDate { get; set; }
        public byte[] Payment { get; set; }
        public string PaymentFileName { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ReviewedBy { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public byte[] FullPaperReview { get; set; }
        public string FullPaperReviewFileName { get; set; }
        public byte[] FullPaperReview2 { get; set; }
        public string FullPaperReviewFileName2 { get; set; }
        public byte[] FullPaperReview3 { get; set; }
        public string FullPaperReviewFileName3 { get; set; }
        public string PaperNumber { get; set; }
        public int SubThemesId { get; set; }
        public int CoAuthors { get; set; }
        public int PaymentType { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public byte[] ProofReadingResult { get; set; }
        public string ProofReadingResultFileName { get; set; }
        public Nullable<int> ProofReaderId { get; set; }
        public Nullable<System.DateTime> ProofReadingDate { get; set; }
        public Nullable<System.DateTime> PaymentVerificationDate { get; set; }
        public bool TermsAgreement { get; set; }
        public byte[] FormatCheckingResult { get; set; }
        public string FormatCheckingResultFileName { get; set; }
        public Nullable<int> FormatCheckerId { get; set; }
        public Nullable<System.DateTime> FormatCheckingDate { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual SubTheme SubTheme { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
