//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icasie.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTheme
    {
        public SubTheme()
        {
            this.Submissions = new HashSet<Submission>();
        }
    
        public int SubThemesId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Submission> Submissions { get; set; }
    }
}
